package com.fastcampus05.zillinks.domain.model.widget;

public enum WidgetType {
    KEYVISUALANDSLOGAN, MISSIONANDVISION, PRODUCTSANDSERVICES, TEAMMEMBER,
    CONTACTUS, NEWS, DOWNLOAD, HISTORY, TEAMCULTURE, PERFORMANCE,
    PARTNERS, REVIEW, CHANNEL, PATENT
}
