server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      default_batch_fetch_size: 100
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl.charset_name: UTF-8
  # hibernateLazyInitializer 오류 해결법
  jackson:
    serialization:
      fail-on-empty-beans: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# aws 설정
# 사용할 S3 bucket region 입력
cloud:
  aws:
    credentials:
      access-key: foobar
      secret-key: foobar
    s3:
      bucket: test-bucket
      delete-dir: http://127.0.0.1:4566/test-bucket/
    region:
      static: ap-northeast-2 # 리전 정보(서울)
    stack:
      auto: false

logging:
  level:
    '[shop.mtcoding.restend]': INFO # DEBUG 레벨부터 에러 확인할 수 있게 설정하기

file:
  path: ./upload/ # UPLOAD 폴더 상대경로 / AWS에 S3 사용하는게 좋음

sentry:
  dsn: {sentry.dsn}
  traces-sample-rate: 1.0
