server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      # oneToMany시에 in query 자동 작성
      default_batch_fetch_size: 100
    # db session controller까지 가져오기
    open-in-view: false
  # hibernateLazyInitializer 오류 해결법
  jackson:
    serialization:
      fail-on-empty-beans: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# aws 설정
# 사용할 S3 bucket region 입력
cloud:
  aws:
    credentials:
      access-key: access-key
      secret-key: secret-key
    s3:
      bucket: bucket-name
    region:
      static: ap-northeast-2 # 리전 정보(서울)
    stack:
      auto: false

logging:
  level:
    '[shop.mtcoding.restend]': DEBUG # DEBUG 레벨부터 에러 확인할 수 있게 설정하기
    '[org.hibernate.type]': TRACE # 콘솔 쿼리에 ? 에 주입된 값 보기

sentry:
  dsn: {sentry.dsn}
  traces-sample-rate: 1.0
